{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fs2-serve.fullname" . }}
  labels:
    {{- include "fs2-serve.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fs2-serve.labels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: http
{{- end }}
