apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
  annotations:
    fs2.nebius.ai/owner: fs2-serve-upstream-addons-live
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    fs2.nebius.ai/owner: fs2-serve-upstream-addons-live
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: kueue-system
  annotations:
    fs2.nebius.ai/owner: fs2-serve-upstream-addons-live
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  annotations:
    fs2.nebius.ai/owner: fs2-serve-upstream-addons-live
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  annotations:
    fs2.nebius.ai/owner: fs2-serve-upstream-addons-live
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
