"""Integration tests against receipts generated by the reference-data producer.

A hand-authored fixture would only prove that this runtime agrees with itself.
These tests therefore import the reference-data implementation and let *it*
generate the terminal receipt through ``_terminal_receipt``, materialize the
published tree with its own ``tree_inventory``, and compute both digests with
its own canonicalization. This runtime's consumer is then checked against that
generated document, and its derivations are compared with the producer's own
``derive_database_root`` and ``derive_preprocess_reference_data``.

The producer implementation is resolved from this repository.
``FS2_AF3_PRODUCER_MODULE`` overrides that path when testing against another
checkout. If neither exposes ``_terminal_receipt`` these tests skip rather than
pretending to have run.
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[3]

BUNDLE = "alphafold3-public-databases-v3.0"
REVISION = "v3.0-paper-snapshot-2022-09-28"
HOST_ROOT = "/mnt/fs2-reference-data/data"
MOUNT_PATH = "/reference-data"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader, path
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


af3 = _load("af3_runtime", ROOT / "runtime" / "af3_runtime.py")


def _producer_module():
    """The reference-data producer implementation, or None if it lacks the API."""
    candidates = []
    override = os.environ.get("FS2_AF3_PRODUCER_MODULE")
    if override:
        candidates.append(Path(override))
    candidates.append(REPO / "reference-data" / "reference_data.py")
    for candidate in candidates:
        if not candidate.is_file():
            continue
        module = _load("reference_data_producer", candidate)
        if hasattr(module, "_terminal_receipt"):
            return module
    return None


producer = _producer_module()

PLACEMENT = {
    "resource_class": "cpu",
    "node_selector": {"fs2.nebius.ai/pool": "reference-data-cpu"},
    "tolerations": [
        {
            "key": "dedicated",
            "operator": "Equal",
            "value": "fs2-reference-data",
            "effect": "NoSchedule",
        }
    ],
}


@unittest.skipIf(
    producer is None,
    "the reference-data producer does not expose _terminal_receipt; set "
    "FS2_AF3_PRODUCER_MODULE to a checkout that does",
)
class ProducerGeneratedReceiptTests(unittest.TestCase):
    """Every document here is generated by the producer, never hand-authored."""

    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)

        # A small but genuine tree using real AlphaFold 3 database target names.
        staging = self.root / "staging"
        (staging / "mmcif_files").mkdir(parents=True)
        (staging / "pdb_seqres_2022_09_28.fasta").write_text(">1abc_A\nMKV\n", encoding="utf-8")
        (staging / "rfam_14_9_clust_seq_id_90_cov_80_rep_seq.fasta").write_text(
            ">RF00001\nGGA\n", encoding="utf-8"
        )
        (staging / "mmcif_files" / "1abc.cif").write_text("data_1ABC\n", encoding="utf-8")

        # The producer computes the aggregate content identity.
        files, self.tree_sha256, self.expanded_bytes = producer.tree_inventory(staging)
        self.file_count = len(files)

        inventory = {
            "schema": producer.INVENTORY_SCHEMA,
            "bundle_id": BUNDLE,
            "revision": REVISION,
            "tree_sha256": self.tree_sha256,
            "expanded_bytes": self.expanded_bytes,
            "file_count": self.file_count,
            "files": files,
        }
        self.inventory_sha256 = producer.sha256_bytes(producer.canonical_json(inventory))

        self.manifest = {
            "schema": producer.MANIFEST_SCHEMA,
            "bundle_id": BUNDLE,
            "revision": REVISION,
            "source_catalog_sha256": "b" * 64,
            "access_receipt_sha256": None,
            "created_at": "2026-09-03T00:00:00Z",
            "content": {
                "tree_sha256": self.tree_sha256,
                "expanded_bytes": self.expanded_bytes,
                "file_count": self.file_count,
                "inventory_sha256": self.inventory_sha256,
                "files": files,
            },
        }
        self.manifest_sha256 = producer.sha256_bytes(
            producer.canonical_json(self.manifest)
        )

        # The receipt is generated by the producer implementation.
        self.receipt = producer._terminal_receipt(
            {"id": BUNDLE, "revision": REVISION},
            self.manifest,
            self.manifest_sha256,
            host_root=HOST_ROOT,
            placement=PLACEMENT,
        )

        # Materialize the tree where the receipt says it lives, under a
        # temporary mount root, and write the publisher's readiness marker.
        self.dataset_sub_path = self.receipt["storage"]["dataset_sub_path"]
        self.tree_root = self.root / self.dataset_sub_path
        self.tree_root.parent.mkdir(parents=True, exist_ok=True)
        staging.rename(self.tree_root)
        (self.tree_root / ".fs2-manifest-sha256").write_text(
            self.manifest_sha256, encoding="utf-8"
        )

        self.manifest_path = (
            self.root / "manifests" / "sha256" / f"{self.manifest_sha256}.json"
        )
        self.manifest_path.parent.mkdir(parents=True, exist_ok=True)
        self.manifest_path.write_text(json.dumps(self.manifest), encoding="utf-8")

    # -- shape agreement ---------------------------------------------------

    def test_the_generated_receipt_has_the_shape_this_runtime_expects(self) -> None:
        self.assertEqual(
            "fs2-serve.nebius.ai/reference-data-terminal-receipt/v1", self.receipt["schema"]
        )
        self.assertEqual(af3.TERMINAL_RECEIPT_SCHEMA, self.receipt["schema"])
        self.assertEqual(af3.TERMINAL_RECEIPT_FIELDS, set(self.receipt))
        self.assertEqual(af3.TERMINAL_STORAGE_FIELDS, set(self.receipt["storage"]))
        self.assertEqual(af3.TERMINAL_CONTENT_FIELDS, set(self.receipt["content"]))
        self.assertEqual(HOST_ROOT, self.receipt["storage"]["host_root"])
        self.assertEqual(MOUNT_PATH, self.receipt["storage"]["mount_path"])
        self.assertTrue(self.receipt["storage"]["read_only"])

    def test_this_runtime_validates_the_generated_receipt(self) -> None:
        validated = af3.validate_terminal_receipt(self.receipt)
        self.assertEqual(self.tree_sha256, validated["content"]["tree_sha256"])
        self.assertEqual(self.manifest_sha256, validated["content"]["manifest_sha256"])
        self.assertEqual(self.inventory_sha256, validated["content"]["inventory_sha256"])
        self.assertNotEqual(
            validated["content"]["tree_sha256"], validated["content"]["manifest_sha256"]
        )

    def test_the_producer_also_validates_it_so_both_sides_agree(self) -> None:
        producer.validate_terminal_receipt(self.receipt)

    def test_the_derived_database_root_matches_the_producers_own_helper(self) -> None:
        self.assertEqual(
            producer.derive_database_root(self.receipt),
            str(af3.derive_database_root(self.receipt)),
        )
        self.assertEqual(
            f"{MOUNT_PATH}/{self.dataset_sub_path}",
            str(af3.derive_database_root(self.receipt)),
        )

    def test_the_dataset_sub_path_ends_in_the_full_tree_digest(self) -> None:
        self.assertEqual(
            f"datasets/{BUNDLE}/{REVISION}/sha256/{self.tree_sha256}", self.dataset_sub_path
        )
        self.assertEqual(self.tree_sha256, Path(self.dataset_sub_path).name)

    # -- mount binding -----------------------------------------------------

    def test_the_runtime_binds_the_mounted_tree_by_name_and_marker(self) -> None:
        binding = af3.bind_reference_tree(
            self.receipt, mount_root=self.root, manifest_path=self.manifest_path
        )
        self.assertEqual(self.tree_root, binding.database_root)
        self.assertEqual(self.tree_sha256, binding.content_tree_sha256)
        self.assertEqual(self.manifest_sha256, binding.manifest_sha256)
        self.assertEqual(self.inventory_sha256, binding.inventory_sha256)
        self.assertTrue(binding.manifest_document_verified)

        emitted = binding.as_receipt()
        self.assertEqual("mounted-tree-name-and-marker", emitted["bound_by"])
        self.assertTrue(emitted["marker_matched_receipt"])
        self.assertTrue(emitted["identities_are_independent"])
        self.assertEqual(HOST_ROOT, emitted["host_root"])
        self.assertEqual(MOUNT_PATH, emitted["mount_path"])
        self.assertEqual(self.tree_sha256, Path(emitted["database_root"]).name)

    def test_a_marker_that_disagrees_with_the_receipt_is_refused(self) -> None:
        (self.tree_root / ".fs2-manifest-sha256").write_text("f" * 64, encoding="utf-8")
        with self.assertRaises(af3.ContractError) as caught:
            af3.bind_reference_tree(self.receipt, mount_root=self.root)
        self.assertIn("not ready for this published revision", str(caught.exception))

    def test_a_missing_marker_means_the_tree_is_not_complete(self) -> None:
        (self.tree_root / ".fs2-manifest-sha256").unlink()
        with self.assertRaises(af3.ContractError) as caught:
            af3.bind_reference_tree(self.receipt, mount_root=self.root)
        self.assertIn("not a complete published tree", str(caught.exception))

    def test_an_unmounted_tree_is_refused(self) -> None:
        with self.assertRaises(af3.ContractError) as caught:
            af3.bind_reference_tree(self.receipt, mount_root=self.root / "elsewhere")
        self.assertIn("not a mounted directory", str(caught.exception))

    def test_a_mismatched_manifest_document_is_refused(self) -> None:
        tampered = dict(self.manifest)
        tampered["revision"] = "tampered"
        self.manifest_path.write_text(json.dumps(tampered), encoding="utf-8")
        with self.assertRaises(af3.ContractError) as caught:
            af3.bind_reference_tree(
                self.receipt, mount_root=self.root, manifest_path=self.manifest_path
            )
        self.assertIn("does not match the receipt identity", str(caught.exception))

    def test_an_explicit_database_root_cannot_redirect_the_mount(self) -> None:
        with self.assertRaises(af3.ContractError) as caught:
            af3.bind_reference_tree(
                self.receipt,
                mount_root=self.root,
                database_root=self.root / "somewhere-else",
            )
        self.assertIn("not the published location", str(caught.exception))

    # -- the transform -----------------------------------------------------

    def test_the_transform_matches_the_producers_own_transform(self) -> None:
        binding = af3.bind_reference_tree(self.receipt, mount_root=self.root)
        manifest_uri = f"file:///reference-data/manifests/sha256/{self.manifest_sha256}.json"
        self.assertEqual(
            producer.derive_preprocess_reference_data(self.receipt, manifest_uri=manifest_uri),
            binding.preprocess_reference_data(manifest_uri),
        )

    def test_the_transform_output_passes_the_producers_request_validator(self) -> None:
        binding = af3.bind_reference_tree(self.receipt, mount_root=self.root)
        manifest_uri = f"file:///reference-data/manifests/sha256/{self.manifest_sha256}.json"
        reference_data = binding.preprocess_reference_data(manifest_uri)
        request = {
            "schema": producer.REQUEST_SCHEMA,
            "request_id": "af3-interop-001",
            "tenant_id": "tenant-example",
            "workload_id": "workload-af3-001",
            "input": {
                "uri": f"file:///inputs/sha256/{'a' * 64}.json",
                "sha256": "a" * 64,
                "bytes": 128,
                "media_type": "application/json",
            },
            "reference_data": reference_data,
            "backend": {
                "kind": "alphafold3-data",
                "database_root": producer.derive_database_root(self.receipt),
                "output_format": "alphafold3-json",
                "threads": 16,
            },
            "privacy": {
                "network_mode": "private-only",
                "public_msa_opt_in": False,
                "log_sequence_content": False,
            },
            "output": {
                "prefix_uri": "file:///results/preprocessing/tenant-example",
                "retention_days": 30,
            },
            "execution": {
                "image": f"registry.example.invalid/af3@sha256:{'d' * 64}",
                "cpu": "16",
                "memory": "64Gi",
                "ephemeral_storage": "32Gi",
                "active_deadline_seconds": 21600,
                "backoff_limit": 2,
            },
        }
        validated = producer.validate_preprocess_request(request)
        self.assertEqual(reference_data, validated["reference_data"])

    def test_a_manifest_uri_that_names_another_digest_is_refused(self) -> None:
        binding = af3.bind_reference_tree(self.receipt, mount_root=self.root)
        with self.assertRaises(af3.ContractError) as caught:
            binding.preprocess_reference_data(
                f"file:///reference-data/manifests/sha256/{'c' * 64}.json"
            )
        self.assertIn("must name the published manifest digest", str(caught.exception))

    # -- invented field names ---------------------------------------------

    def test_invented_handoff_field_names_are_refused_by_both_sides(self) -> None:
        for alias in ("published_manifest_sha256", "source_sub_path", "manifest_digest"):
            with self.subTest(alias=alias):
                broken = json.loads(json.dumps(self.receipt))
                broken["storage"][alias] = "x"
                with self.assertRaises(af3.ContractError):
                    af3.validate_terminal_receipt(broken)
                with self.assertRaises(producer.ContractError):
                    producer.validate_terminal_receipt(broken)

    def test_the_old_shared_filesystem_uri_shape_is_refused(self) -> None:
        """The earlier invented shape must never be accepted again."""
        broken = json.loads(json.dumps(self.receipt))
        broken["storage"]["shared_filesystem_uri"] = "file:///mnt/whatever"
        with self.assertRaises(af3.ContractError) as caught:
            af3.validate_terminal_receipt(broken)
        self.assertIn("does not exist", str(caught.exception))

    def test_a_receipt_that_reserves_a_gpu_is_refused(self) -> None:
        broken = json.loads(json.dumps(self.receipt))
        broken["placement"]["node_selector"]["nebius.com/gpu"] = "H100"
        with self.assertRaises(af3.ContractError) as caught:
            af3.validate_terminal_receipt(broken)
        self.assertIn("must not declare an accelerator node selector", str(caught.exception))

    def test_a_receipt_with_a_wrong_host_root_is_refused(self) -> None:
        broken = json.loads(json.dumps(self.receipt))
        broken["storage"]["host_root"] = "/mnt/somewhere-else"
        with self.assertRaises(af3.ContractError) as caught:
            af3.validate_terminal_receipt(broken)
        self.assertIn("shared reference filesystem", str(caught.exception))

    def test_a_receipt_with_a_wrong_mount_path_is_refused(self) -> None:
        broken = json.loads(json.dumps(self.receipt))
        broken["storage"]["mount_path"] = "/somewhere-else"
        with self.assertRaises(af3.ContractError) as caught:
            af3.validate_terminal_receipt(broken)
        self.assertIn("reference mount", str(caught.exception))

    def test_a_writable_tree_is_refused(self) -> None:
        broken = json.loads(json.dumps(self.receipt))
        broken["storage"]["read_only"] = False
        with self.assertRaises(af3.ContractError) as caught:
            af3.validate_terminal_receipt(broken)
        self.assertIn("read-only", str(caught.exception))


if __name__ == "__main__":
    unittest.main()
