import type {
  AdminCapacity,
  AdminMeasurement,
  AdminObservability,
} from "../api/types.ts";

export const capacityObservedAt = "2026-08-30T09:00:00Z";

export function capacityMeasurement(
  value: number | null,
  unit: string,
  state: AdminMeasurement["state"] = value === null ? "unavailable" : "available",
  reason: string | null = value === null ? "accepted source did not report this value" : null,
  source = "kubernetes",
): AdminMeasurement {
  return { value, unit, state, source, reason };
}

const quantity = (value: string | null, reason: string | null = null) => ({
  value,
  state: value === null ? "unavailable" as const : "available" as const,
  source: "kueue",
  reason: value === null ? reason ?? "Kueue status did not publish this quantity" : null,
});

const zeroWorkloads = {
  pending: capacityMeasurement(0, "count"),
  reserving: capacityMeasurement(0, "count"),
  admitted: capacityMeasurement(0, "count"),
};

export const capacityFixture: AdminCapacity = {
  node_pools: {
    state: "available",
    reason: null,
    items: [
      {
        id: "pool-001122aabbcc",
        pool_label: "burst-blackwell",
        instance_type: "gpu-8x-large",
        gpu_class: "accelerator-288gb",
        capacity_type: "preemptible",
        nodes: {
          total: capacityMeasurement(2, "nodes"),
          ready: capacityMeasurement(2, "nodes"),
          not_ready: capacityMeasurement(0, "nodes"),
          unschedulable: capacityMeasurement(0, "nodes"),
        },
        gpu_resources: [{
          resource_name: "nvidia.com/gpu",
          capacity: capacityMeasurement(16, "gpus"),
          allocatable: capacityMeasurement(16, "gpus"),
          allocated: capacityMeasurement(0, "gpus", "estimated", "derived from scheduled Pod requests"),
          healthy: capacityMeasurement(null, "gpus", "unavailable", "explicit GPU health evidence is unavailable", "dcgm"),
        }],
      },
      {
        id: "pool-ddeeffaabbcc",
        pool_label: "steady-hopper",
        instance_type: "gpu-8x-standard",
        gpu_class: "accelerator-141gb",
        capacity_type: "regular",
        nodes: {
          total: capacityMeasurement(1, "nodes"),
          ready: capacityMeasurement(1, "nodes"),
          not_ready: capacityMeasurement(0, "nodes"),
          unschedulable: capacityMeasurement(0, "nodes"),
        },
        gpu_resources: [{
          resource_name: "nvidia.com/gpu",
          capacity: capacityMeasurement(8, "gpus"),
          allocatable: capacityMeasurement(8, "gpus"),
          allocated: capacityMeasurement(5, "gpus", "estimated", "derived from scheduled Pod requests"),
          healthy: capacityMeasurement(8, "gpus", "available", null, "dcgm"),
        }],
      },
      {
        id: "pool-123456abcdef",
        pool_label: null,
        instance_type: null,
        gpu_class: "accelerator-vendor-neutral",
        capacity_type: "unknown",
        nodes: {
          total: capacityMeasurement(1, "nodes"),
          ready: capacityMeasurement(0, "nodes"),
          not_ready: capacityMeasurement(1, "nodes"),
          unschedulable: capacityMeasurement(1, "nodes"),
        },
        gpu_resources: [{
          resource_name: "accelerator.example/gpu",
          capacity: capacityMeasurement(4, "gpus"),
          allocatable: capacityMeasurement(0, "gpus"),
          allocated: capacityMeasurement(null, "gpus", "unavailable", "scheduled Pod requests are unavailable"),
          healthy: capacityMeasurement(null, "gpus", "unavailable", "device telemetry is unavailable", "device-metrics"),
        }],
      },
    ],
  },
  kueue: {
    state: "available",
    reason: null,
    resource_flavors: [
      { name: "burst-288gb", capacity_type: "preemptible", gpu_class: "accelerator-288gb" },
      { name: "steady-141gb", capacity_type: "regular", gpu_class: "accelerator-141gb" },
    ],
    cluster_queues: [{
      name: "inference",
      cohort: "shared-accelerators",
      queueing_strategy: "BestEffortFIFO",
      stop_policy: null,
      active: true,
      workloads: zeroWorkloads,
      resources: [{
        flavor: "burst-288gb",
        resource_name: "nvidia.com/gpu",
        nominal_quota: quantity("32"),
        reservation: quantity("0"),
        usage: quantity("0"),
        borrowed: quantity(null, "borrowing status is not published"),
      }],
    }],
    local_queues: [{
      namespace: "fs2-models",
      name: "models",
      cluster_queue: "inference",
      stop_policy: null,
      active: true,
      workloads: zeroWorkloads,
    }],
    cohorts: [{ name: "shared-accelerators", parent: null }],
    cohorts_state: "available",
    cohorts_reason: null,
    workloads: [],
    workloads_truncated: false,
  },
  autoscaling: {
    hpa: {
      state: "available",
      reason: null,
      horizontal_pod_autoscalers: [{
        namespace: "fs2-system",
        name: "control-plane",
        target_kind: "Deployment",
        target_name: "fs2-control-plane",
        min_replicas: capacityMeasurement(2, "replicas"),
        max_replicas: capacityMeasurement(8, "replicas"),
        current_replicas: capacityMeasurement(2, "replicas"),
        desired_replicas: capacityMeasurement(2, "replicas"),
        able_to_scale: true,
        scaling_active: false,
        scaling_limited: null,
      }],
    },
    keda: { state: "available", reason: null, keda_scaled_objects: [] },
  },
  node_scaler: {
    state: "unavailable",
    provider: null,
    configured: null,
    healthy: null,
    observed_at: null,
    reason: "provider node-scaler adapter is not configured",
  },
};

export const observabilityFixture: AdminObservability = {
  components: [
    {
      id: "grafana",
      display_name: "Grafana",
      installed: true,
      health: "healthy",
      data_present: true,
      launch: { enabled: true, url: "https://console.example.test/admin/observability/grafana/", reason: null },
      version: "12.2.0",
      observed_at: capacityObservedAt,
      reason: null,
    },
    {
      id: "prometheus",
      display_name: "Prometheus",
      installed: true,
      health: "healthy",
      data_present: true,
      launch: { enabled: false, url: null, reason: "raw Prometheus remains private" },
      version: "3.5.0",
      observed_at: capacityObservedAt,
      reason: null,
    },
    {
      id: "loki",
      display_name: "Loki",
      installed: true,
      health: "degraded",
      data_present: true,
      launch: { enabled: true, url: "https://console.example.test/admin/observability/grafana/explore?var-cluster=cluster-test", reason: null },
      version: "3.5.3",
      observed_at: capacityObservedAt,
      reason: "one or more component targets are unhealthy",
    },
    {
      id: "otel",
      display_name: "OpenTelemetry Collector",
      installed: true,
      health: "healthy",
      data_present: true,
      launch: { enabled: false, url: null, reason: "OpenTelemetry has no direct operator UI" },
      version: "0.132.0",
      observed_at: capacityObservedAt,
      reason: null,
    },
    {
      id: "dcgm",
      display_name: "NVIDIA DCGM",
      installed: true,
      health: "unknown",
      data_present: false,
      launch: { enabled: false, url: null, reason: "no verified dashboard route" },
      version: null,
      observed_at: capacityObservedAt,
      reason: "component has no accepted Prometheus target",
    },
    {
      id: "kueue",
      display_name: "Kueue",
      installed: true,
      health: "healthy",
      data_present: false,
      launch: { enabled: false, url: null, reason: "no verified dashboard route" },
      version: "0.17.8",
      observed_at: capacityObservedAt,
      reason: null,
    },
    {
      id: "keda",
      display_name: "KEDA",
      installed: true,
      health: "healthy",
      data_present: false,
      launch: { enabled: false, url: null, reason: "no verified dashboard route" },
      version: "2.20.2",
      observed_at: capacityObservedAt,
      reason: null,
    },
    {
      id: "alertmanager",
      display_name: "Alertmanager",
      installed: false,
      health: "unknown",
      data_present: null,
      launch: { enabled: false, url: null, reason: "component is not installed" },
      version: null,
      observed_at: capacityObservedAt,
      reason: "component is configured as not installed",
    },
    {
      id: "tempo",
      display_name: "Tempo",
      installed: null,
      health: "unknown",
      data_present: null,
      launch: { enabled: false, url: null, reason: "component probe is unavailable" },
      version: null,
      observed_at: null,
      reason: "component probe is unavailable",
    },
  ],
  signals: {
    gpu_utilization_ratio: capacityMeasurement(null, "ratio", "unavailable", "accepted metric series is unavailable", "dcgm"),
    gpu_memory_utilization_ratio: capacityMeasurement(null, "ratio", "unavailable", "accepted metric series is unavailable", "dcgm"),
    otel_refused_items_per_second: capacityMeasurement(0, "items/second", "available", null, "prometheus"),
    otel_export_failures_per_second: capacityMeasurement(0, "items/second", "available", null, "prometheus"),
  },
};
