"""Versioned fs2-serve model catalog and gateway consumer API."""

from .artifacts import ArtifactManifest, build_artifact_manifest, load_artifact_manifest
from .acquisition import acquire_huggingface_artifact, finalize_acquisition_receipt
from .attestations import create_signed_attestation, public_key_id, public_key_value
from .capabilities import BackendCapability, bind_backend_capability
from .consumer import (
    ActivationBinding,
    GatewayCatalog,
    GatewayModel,
    ServingBinding,
    ServingBindings,
    bind_gateway_catalog,
    contract_fixture,
    identity_map,
    load_gateway_catalog,
    load_serving_bindings,
)
from .evidence import (
    AcquisitionHelperImageAdmission,
    FaststartJobAdmission,
    ProtectedStorageClassAdmission,
    ProviderBlockWriterAdmission,
    load_acquisition_helper_image_admission,
    load_faststart_job_admission,
    load_protected_storage_class_admission,
    load_provider_block_writer_admission,
)
from .loader import (
    AcquisitionPlan,
    Catalog,
    CatalogError,
    FallbackCandidate,
    FederatedBackend,
    ModelRecord,
    ModelVariant,
    SemanticRequestContract,
    ScaleContract,
    load_catalog,
)
from .volume_ownership import (
    FS_GROUP_CHANGE_POLICY,
    VolumeOwnershipError,
    apply_filesystem_group,
    assert_pod_volume_ownership,
    filesystem_group_security_context,
    validate_pod_volume_ownership,
)
from .prerequisites import PrerequisiteBinding, bind_runtime_prerequisites
from .package import installed_catalog_root
from .staging import stage_artifact
from .workloads import replica_field_ownership, render_runtime_network_policy
from .variant_promotions import (
    VariantGatewayCatalog,
    VariantGatewayModel,
    VariantPromotion,
    VariantPromotions,
    bind_variant_gateway_catalog,
    load_model_variant_promotions,
    load_variant_gateway_catalog,
    variant_promotion_contract_fixture,
)

__all__ = [
    "Catalog",
    "CatalogError",
    "FS_GROUP_CHANGE_POLICY",
    "FilesystemGroupConsumer",
    "FilesystemGroupProducer",
    "VolumeOwnershipError",
    "apply_filesystem_group",
    "assert_authority",
    "assert_pod_volume_ownership",
    "authority_violations",
    "filesystem_group_security_context",
    "validate_pod_volume_ownership",
    "AcquisitionPlan",
    "AcquisitionHelperImageAdmission",
    "ActivationBinding",
    "acquire_huggingface_artifact",
    "finalize_acquisition_receipt",
    "ArtifactManifest",
    "BackendCapability",
    "GatewayCatalog",
    "GatewayModel",
    "FederatedBackend",
    "FallbackCandidate",
    "FaststartJobAdmission",
    "ProtectedStorageClassAdmission",
    "ProviderBlockWriterAdmission",
    "ModelRecord",
    "ModelVariant",
    "PrerequisiteBinding",
    "ServingBinding",
    "ServingBindings",
    "SemanticRequestContract",
    "ScaleContract",
    "bind_gateway_catalog",
    "bind_backend_capability",
    "bind_runtime_prerequisites",
    "contract_fixture",
    "identity_map",
    "installed_catalog_root",
    "build_artifact_manifest",
    "create_signed_attestation",
    "load_catalog",
    "load_artifact_manifest",
    "load_acquisition_helper_image_admission",
    "load_gateway_catalog",
    "load_faststart_job_admission",
    "load_protected_storage_class_admission",
    "load_provider_block_writer_admission",
    "load_serving_bindings",
    "public_key_id",
    "public_key_value",
    "replica_field_ownership",
    "render_runtime_network_policy",
    "stage_artifact",
    "VariantGatewayCatalog",
    "VariantGatewayModel",
    "VariantPromotion",
    "VariantPromotions",
    "bind_variant_gateway_catalog",
    "load_model_variant_promotions",
    "load_variant_gateway_catalog",
    "variant_promotion_contract_fixture",
]
