"""Materialize tenant-owned bulk inputs only at the runtime boundary.

MCP tool arguments and durable admission rows retain small immutable artifact
references.  The worker verifies ownership and content identity, then expands
only schema fields explicitly marked by ``model_input_contracts`` immediately
before invoking the selected runtime.  Raw file bytes therefore never need to
be generated by a language model or copied into its context.
"""

# ruff: noqa: F811 -- the additive fail-closed successor preserves the reviewed base class.

from __future__ import annotations

import base64
import json
from dataclasses import dataclass
from typing import Any, Final, Literal
from uuid import UUID

from .model_input_contracts import InputContractUnavailable, contract_for, packaged_input_fixture
from .registry import OperationalModel
from .runtime import RuntimeOperationError
from .scientific_artifacts import ScientificArtifactControllerPort
from .scientific_run_result import ArtifactRef, Compression

Materialization = Literal["utf-8", "base64", "data-url", "json"]
PathPart = str | None

_MATERIALIZATION_KEY: Final = "x-fs2-artifact-materialization"
_MAX_BYTES_KEY: Final = "x-fs2-artifact-max-bytes"
_MEDIA_TYPES_KEY: Final = "x-fs2-artifact-media-types"
_REQUEST_MAX_BYTES_KEY: Final = "x-fs2-artifact-request-max-bytes"


class ArtifactInputError(RuntimeOperationError):
    """A referenced input cannot be safely converted to the runtime DTO."""

    code = "artifact_input_invalid"
    status_code = 422


@dataclass(frozen=True, slots=True)
class _Rule:
    path: tuple[PathPart, ...]
    materialization: Materialization
    max_bytes: int
    media_types: frozenset[str]


def _local_ref(root: dict[str, Any], reference: str) -> Any:
    if not reference.startswith("#/"):
        raise ArtifactInputError("artifact input schema contains a non-local reference")
    value: Any = root
    for raw in reference[2:].split("/"):
        part = raw.replace("~1", "/").replace("~0", "~")
        if not isinstance(value, dict) or part not in value:
            raise ArtifactInputError("artifact input schema reference is unresolved")
        value = value[part]
    return value


def _rules(schema: dict[str, Any]) -> tuple[_Rule, ...]:
    found: dict[tuple[PathPart, ...], _Rule] = {}

    def visit(value: Any, path: tuple[PathPart, ...], active_refs: frozenset[str]) -> None:
        if not isinstance(value, dict):
            return
        mode = value.get(_MATERIALIZATION_KEY)
        if mode is not None:
            if mode not in {"utf-8", "base64", "data-url", "json"}:
                raise ArtifactInputError("artifact input schema has an unknown materialization")
            maximum = value.get(_MAX_BYTES_KEY)
            media_types = value.get(_MEDIA_TYPES_KEY)
            if not isinstance(maximum, int) or maximum < 1:
                raise ArtifactInputError("artifact input schema has an invalid byte limit")
            if not isinstance(media_types, list) or not media_types or not all(
                isinstance(item, str) for item in media_types
            ):
                raise ArtifactInputError("artifact input schema has invalid media types")
            rule = _Rule(path, mode, maximum, frozenset(media_types))
            previous = found.get(path)
            if (
                previous is not None
                and previous.path == rule.path
                and previous.materialization == rule.materialization
                and previous.max_bytes == rule.max_bytes
            ):
                found[path] = _Rule(
                    path,
                    mode,
                    maximum,
                    previous.media_types | rule.media_types,
                )
                return
            if previous is not None and previous != rule:
                raise ArtifactInputError("artifact input schema has conflicting transports")
            found[path] = rule
            return
        reference = value.get("$ref")
        if isinstance(reference, str) and reference not in active_refs:
            visit(_local_ref(schema, reference), path, active_refs | {reference})
        properties = value.get("properties")
        if isinstance(properties, dict):
            for name, child in properties.items():
                visit(child, path + (name,), active_refs)
        items = value.get("items")
        if isinstance(items, dict):
            visit(items, path + (None,), active_refs)
        elif isinstance(items, list):
            for child in items:
                visit(child, path + (None,), active_refs)
        prefix_items = value.get("prefixItems")
        if isinstance(prefix_items, list):
            for child in prefix_items:
                visit(child, path + (None,), active_refs)
        for keyword in ("allOf", "anyOf", "oneOf"):
            alternatives = value.get(keyword)
            if isinstance(alternatives, list):
                for child in alternatives:
                    visit(child, path, active_refs)
        for keyword in (
            "if",
            "then",
            "else",
            "not",
            "contains",
            "additionalProperties",
            "unevaluatedProperties",
            "unevaluatedItems",
        ):
            child = value.get(keyword)
            if isinstance(child, dict):
                visit(child, path, active_refs)

    visit(schema, (), frozenset())
    return tuple(found[path] for path in sorted(found, key=lambda item: tuple("*" if x is None else x for x in item)))


def _slots(value: Any, path: tuple[PathPart, ...]) -> list[tuple[Any, str | int]]:
    if not path:
        return []
    current: list[tuple[Any, PathPart]] = [(value, path[0])]
    for part in path[1:]:
        next_values: list[tuple[Any, PathPart]] = []
        for parent, key in current:
            child: Any
            if key is None:
                if not isinstance(parent, list):
                    continue
                for item in parent:
                    next_values.append((item, part))
                continue
            if not isinstance(parent, dict) or key not in parent:
                continue
            child = parent[key]
            next_values.append((child, part))
        current = next_values
    result: list[tuple[Any, str | int]] = []
    for parent, key in current:
        if key is None:
            if isinstance(parent, list):
                result.extend((parent, index) for index in range(len(parent)))
        elif isinstance(parent, dict) and key in parent:
            result.append((parent, key))
    return result


def _enforce_request_budget(payload: dict[str, Any], schema: dict[str, Any]) -> None:
    """Reject declared artifact sets before opening or buffering any stream."""

    maximum = schema.get(_REQUEST_MAX_BYTES_KEY)
    if maximum is None:
        return
    if not isinstance(maximum, int) or maximum < 1:
        raise ArtifactInputError("artifact input schema has an invalid request byte limit")
    total = 0
    for rule in _rules(schema):
        for parent, key in _slots(payload, rule.path):
            descriptor = parent[key]
            if not isinstance(descriptor, dict) or "artifact_id" not in descriptor:
                continue
            try:
                reference = ArtifactRef.model_validate(descriptor)
            except (TypeError, ValueError) as error:
                raise ArtifactInputError("artifact input reference is invalid") from error
            total += reference.size_bytes
            if total > maximum:
                raise ArtifactInputError("artifact inputs exceed the model request byte limit")


class ArtifactInputMaterializer:
    """Resolve only explicitly transport-enabled fields for the owning tenant."""

    def __init__(self, artifacts: ScientificArtifactControllerPort) -> None:
        self._artifacts = artifacts

    async def _artifact_bytes(
        self, descriptor: dict[str, Any], *, tenant_id: str, rule: _Rule
    ) -> tuple[bytes, str]:
        try:
            reference = ArtifactRef.model_validate(descriptor)
            artifact_id = UUID(reference.artifact_id)
        except (TypeError, ValueError) as error:
            raise ArtifactInputError("artifact input reference is invalid") from error
        if reference.compression is not Compression.NONE:
            raise ArtifactInputError("compressed model input artifacts are not supported")
        if reference.size_bytes > rule.max_bytes or reference.media_type not in rule.media_types:
            raise ArtifactInputError("artifact input metadata is outside the model field contract")
        stream = await self._artifacts.open_content(artifact_id, tenant_id=tenant_id)
        actual = stream.artifact.to_public_ref()
        if actual != reference:
            raise ArtifactInputError("artifact input metadata does not match stored content")
        chunks = bytearray()
        async for chunk in stream.chunks:
            if len(chunks) + len(chunk) > rule.max_bytes:
                raise ArtifactInputError("artifact input exceeds the model field byte limit")
            chunks.extend(chunk)
        if len(chunks) != reference.size_bytes:
            raise ArtifactInputError("artifact input stream is incomplete")
        return bytes(chunks), reference.media_type

    @staticmethod
    def _fixture_bytes(descriptor: dict[str, Any], *, rule: _Rule) -> tuple[bytes, str]:
        if set(descriptor) != {"fixture_id"} or not isinstance(descriptor["fixture_id"], str):
            raise ArtifactInputError("fixture input reference is invalid")
        try:
            content, media_type = packaged_input_fixture(descriptor["fixture_id"])
        except KeyError as error:
            raise ArtifactInputError("fixture input reference is unknown") from error
        if len(content) > rule.max_bytes or media_type not in rule.media_types:
            raise ArtifactInputError("fixture is outside the model field contract")
        return content, media_type

    @staticmethod
    def _decode(content: bytes, media_type: str, mode: Materialization) -> Any:
        if mode == "base64":
            return base64.b64encode(content).decode("ascii")
        if mode == "data-url":
            return f"data:{media_type};base64,{base64.b64encode(content).decode('ascii')}"
        try:
            text = content.decode("utf-8")
        except UnicodeDecodeError as error:
            raise ArtifactInputError("artifact input is not valid UTF-8") from error
        if mode == "utf-8":
            return text
        try:
            return json.loads(text)
        except json.JSONDecodeError as error:
            raise ArtifactInputError("artifact input is not valid JSON") from error

    async def materialize(
        self,
        model: OperationalModel,
        protocol: str,
        *,
        tenant_id: str,
        request_body: bytes,
    ) -> bytes:
        if b"\\u" in request_body:
            try:
                escaped_payload = json.loads(request_body)
                request_body = json.dumps(
                    escaped_payload,
                    sort_keys=True,
                    separators=(",", ":"),
                    ensure_ascii=False,
                    allow_nan=False,
                ).encode("utf-8")
            except (TypeError, ValueError, UnicodeDecodeError, json.JSONDecodeError) as error:
                raise ArtifactInputError("artifact-backed model input must be canonical JSON") from error
        if b'"artifact_id"' not in request_body and b'"fixture_id"' not in request_body:
            return request_body
        try:
            payload = json.loads(request_body)
        except json.JSONDecodeError as error:
            raise ArtifactInputError("artifact-backed model input must be JSON") from error
        if not isinstance(payload, dict):
            raise ArtifactInputError("artifact-backed model input must be an object")
        try:
            contract = contract_for(model, protocol)
        except InputContractUnavailable as error:
            raise ArtifactInputError("artifact-backed input has no selected runtime contract") from error
        _enforce_request_budget(payload, contract.input_schema)
        matched = False
        for rule in _rules(contract.input_schema):
            for parent, key in _slots(payload, rule.path):
                descriptor = parent[key]
                if not isinstance(descriptor, dict):
                    continue
                if "artifact_id" in descriptor:
                    content, media_type = await self._artifact_bytes(descriptor, tenant_id=tenant_id, rule=rule)
                elif "fixture_id" in descriptor:
                    content, media_type = self._fixture_bytes(descriptor, rule=rule)
                else:
                    continue
                parent[key] = self._decode(content, media_type, rule.materialization)
                matched = True
        if not matched:
            raise ArtifactInputError("artifact or fixture reference is not allowed at this model input field")
        try:
            return json.dumps(
                payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
            ).encode("utf-8")
        except (TypeError, ValueError) as error:
            raise ArtifactInputError("materialized model input is not canonical JSON") from error


class ArtifactInputMaterializer(ArtifactInputMaterializer):
    """Normalize permanent artifact-resolution failures at the input boundary."""

    async def _artifact_bytes(
        self, descriptor: dict[str, Any], *, tenant_id: str, rule: _Rule
    ) -> tuple[bytes, str]:
        from .scientific_artifacts import (
            ArtifactConflictError,
            ArtifactContentTooLargeError,
            ArtifactNotFoundError,
            ArtifactPolicyError,
            ArtifactVerificationError,
            StaleArtifactAttemptError,
        )

        try:
            return await super()._artifact_bytes(descriptor, tenant_id=tenant_id, rule=rule)
        except (
            ArtifactConflictError,
            ArtifactContentTooLargeError,
            ArtifactNotFoundError,
            ArtifactPolicyError,
            ArtifactVerificationError,
            StaleArtifactAttemptError,
        ) as error:
            raise ArtifactInputError("artifact input could not be resolved") from error


__all__ = ["ArtifactInputError", "ArtifactInputMaterializer"]
