"""Build bounded typed AMBER ligand-preparation and GB/PB analysis workflows."""

import argparse
import hashlib
import io
import json
import math
import tarfile
from pathlib import Path


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def benzene_pdb():
    # Explicit synthetic geometry, not an experimental structure claim.
    lines = ["REMARK Synthetic planar benzene: CC1.397A and CH1.09A\n"]
    for number in range(12):
        carbon = number < 6
        angle = (number % 6) * math.pi / 3
        radius = 1.397 if carbon else 2.487
        atom = ("C" if carbon else "H") + str(number % 6 + 1)
        element = "C" if carbon else "H"
        lines.append(f"HETATM{number + 1:5d} {atom:<4s} BEN A   1    {radius * math.cos(angle):8.3f}{radius * math.sin(angle):8.3f}{0.0:8.3f}  1.00  0.00          {element:>2s}\n")
    for number in range(6):
        lines.append(f"CONECT{number + 1:5d}{(number + 1) % 6 + 1:5d}{(number - 1) % 6 + 1:5d}{number + 7:5d}\n")
    return ("".join(lines) + "END\n").encode()


def make(source, output):
    output.mkdir(parents=True, exist_ok=False, mode=0o700)
    files = {"benzene/benzene.pdb": benzene_pdb(), "benzene/prepare.leap": b"source leaprc.gaff2\nloadamberparams benzene.frcmod\nligand = loadmol2 benzene.mol2\ncheck ligand\nsaveamberparm ligand benzene.prmtop benzene.inpcrd\nquit\n", "benzene/inspect.in": b"summary\ncheckValidity\nprintInfo CHARGE\nquit\n"}
    for name in ("ras-raf.prmtop", "ras-raf_solvated.prmtop", "ras.prmtop", "raf.prmtop", "prod.mdcrd"):
        files["ras-raf/" + name] = (source / "inputs" / name).read_bytes()
    files["ras-raf/mmpbsa.in"] = b"Bounded official Ras-Raf GB/PB control,5frames,no entropy estimate\n&general\n startframe=1, endframe=5, interval=1, verbose=2, keep_files=2, use_sander=1,\n/\n&gb\n igb=2, saltcon=0.100, surften=0.0072,\n/\n&pb\n istrng=0.100,\n/\n"
    # These explicit native MDIN inputs were generated by the pinned tool.
    # GB external dielectric78.3 matches the published reference; no worker
    # rewrite or implication that the current default80.0 is equivalent.
    for model in ("gb", "pb"):
        files[f"ras-raf/binding.intermediate_{model}.mdin"] = (source / "native-v2-matched-gb/ras-raf" / ("_MMPBSA_" + model + ".mdin")).read_bytes()
    # Native PB analysis also has a distinct ligand mdin2; retaining only
    # the primary PB mdin is an incomplete native context, not a valid bundle.
    files["ras-raf/binding.intermediate_pb.mdin2"] = (source / "native-v2-matched-gb/ras-raf/_MMPBSA_pb.mdin2").read_bytes()
    steps = [
        {"id": "charge-ligand", "kind": "antechamber", "directory": "benzene", "input": "benzene.pdb", "input_format": "pdb", "output": "benzene.mol2", "atom_types": "gaff2", "net_charge": 0, "residue_name": "BEN", "charge_equivalence": 1, "charge_tolerance_e": 0.001, "expected_outputs": ["benzene.mol2", "sqm.out"]},
        {"id": "parameters", "kind": "parmchk2", "directory": "benzene", "input": "benzene.mol2", "input_format": "mol2", "output": "benzene.frcmod", "atom_types": "gaff2"},
        {"id": "prepare-ligand", "kind": "tleap", "directory": "benzene", "input": "prepare.leap", "expected_outputs": ["benzene.prmtop", "benzene.inpcrd"]},
        {"id": "inspect-ligand", "kind": "parmed", "directory": "benzene", "input": "inspect.in", "topology": "benzene.prmtop", "coordinates": "benzene.inpcrd", "expected_outputs": ["fs2-inspect-ligand.stdout.log"]},
        {"id": "binding", "kind": "mmpbsa", "directory": "ras-raf", "input": "mmpbsa.in", "complex_topology": "ras-raf.prmtop", "receptor_topology": "ras.prmtop", "ligand_topology": "raf.prmtop", "solvated_topology": "ras-raf_solvated.prmtop", "trajectories": ["prod.mdcrd"], "expected_frames": 5, "output_prefix": "binding", "use_mdins": True},
    ]
    protocol = {"fixture": "advanced-tools", "ligand": "synthetic benzene C6H6,GAFF2 AM1-BCC", "binding": "official Ras-Raf tutorial first5frames,GB(igb2,extdiel78.3)+PB,no entropy", "source_urls": ["https://ambermd.org/tutorials/advanced/tutorial3/py_script/section1.php", "https://ambermd.org/tutorials/advanced/tutorial3/py_script/files/ras-raf_top_mdcrd.tgz"], "preserved_separate_failures": ["Official Sustiva native charge residual-0.002e exceeds the default0.001e gate; never silently renormalized", "Legacy2010 five-frame energies on newly aligned/rounded trajectories are not an exact Cartesian accuracy control; separately check unchanged published component coordinates"], "force_field_suitability_claimed": False, "free_energy_convergence_claimed": False, "scientific_convergence_claimed": False}
    files["protocol.json"] = json.dumps(protocol, indent=2).encode() + b"\n"
    request = {"schema": "fs2-serve.nebius.ai/amber-workflow-request/v1", "backend": "cpu", "threads": 1, "max_wall_seconds": 3600, "max_output_bytes": 1024**3, "jobs": [{"id": "advanced-tools", "steps": steps}]}
    (output / "request.json").write_text(json.dumps(request, indent=2) + "\n")
    with tarfile.open(output / "input.tar.gz", "w:gz") as archive:
        for name, raw in sorted(files.items()):
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.mtime = len(raw), 0o644, 0
            archive.addfile(info, io.BytesIO(raw))
    manifest = {"input_sha256": sha((output / "input.tar.gz").read_bytes()), "request_sha256": sha((output / "request.json").read_bytes()), "files": [{"path": name, "sha256": sha(raw), "size_bytes": len(raw)} for name, raw in sorted(files.items())], "protocol": protocol}
    (output / "fixture-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(make(args.source, args.output)))


if __name__ == "__main__":
    main()
