"""Deterministic staged scientific-batch controller contracts."""

from .catalog_adapter import (
    CatalogProfileAdapterError,
    ScientificStageExpansion,
    scientific_plan_from_catalog_profile,
)
from .controller import ScientificBatchController
from .models import (
    ArtifactCommit,
    AttemptOutcome,
    BatchClaim,
    BatchEvent,
    BatchEventDraft,
    BatchEventKind,
    BatchStatus,
    CheckpointMode,
    ExecutionMode,
    FailureKind,
    LifecyclePhase,
    PreemptionMode,
    ResourceClass,
    SchedulingSnapshot,
    ScientificAttemptState,
    ScientificBatchPlan,
    ScientificBatchState,
    ScientificStagePlan,
    ScientificStageState,
    ServiceClass,
    StageSchedulingDecision,
    StageStatus,
    WorkloadKind,
    WorkloadObservation,
    WorkloadRef,
    WorkloadResource,
    WorkloadState,
)
from .protocols import (
    BatchFenceLostError,
    BatchRepositoryConflictError,
    ScientificBatchCluster,
    ScientificBatchRepository,
)

__all__ = [
    "ArtifactCommit",
    "AttemptOutcome",
    "BatchClaim",
    "BatchEvent",
    "BatchEventDraft",
    "BatchEventKind",
    "BatchFenceLostError",
    "ScientificBatchPlan",
    "ScientificBatchState",
    "BatchRepositoryConflictError",
    "BatchStatus",
    "CatalogProfileAdapterError",
    "CheckpointMode",
    "ExecutionMode",
    "FailureKind",
    "LifecyclePhase",
    "PreemptionMode",
    "ResourceClass",
    "SchedulingSnapshot",
    "ScientificBatchCluster",
    "ScientificBatchController",
    "ScientificBatchRepository",
    "ScientificAttemptState",
    "ScientificStageExpansion",
    "ScientificStageState",
    "StageSchedulingDecision",
    "ScientificStagePlan",
    "ServiceClass",
    "StageStatus",
    "WorkloadKind",
    "WorkloadObservation",
    "WorkloadRef",
    "WorkloadResource",
    "WorkloadState",
    "scientific_plan_from_catalog_profile",
]
