from __future__ import annotations

import json
import unittest
from dataclasses import replace
from datetime import UTC, datetime
from pathlib import Path

import pytest

from fs2_serve.registry import Registry, RegistryError
from fs2_serve.scientific_admin import ScientificAdminSourceUnavailableError, ScientificModelSnapshot
from fs2_serve.scientific_admin_catalog import (
    CandidateRouteScope,
    ScientificCatalogFileAdapter,
    ScientificProfileDiscoveryAdapter,
    _execution_identity_join,
    scientific_receipts_file,
)
from fs2_serve.scientific_admin_models import ScientificModelReadinessList
from fs2_serve.scientific_batch.service import ScientificProfileDiscovery

FIXED_NOW = datetime(2026, 9, 2, 21, 0, tzinfo=UTC)

# The projection is exercised against admin-owned fixtures rather than the
# delivered catalog. Scientific receipts and workload profiles are generated by
# the model-onboarding workstream, so binding these assertions to the shipped
# catalog would make this suite fail whenever that producer regenerates it.
FIXTURES = Path(__file__).resolve().parent / "fixtures/scientific-admin-catalog"
RECEIPTS = FIXTURES / "scientific-source-candidate-receipts.json"
ACADEMIC_READINESS = FIXTURES / "academic-asset-readiness.json"

DELIVERED_CATALOG = Path(__file__).resolve().parents[3] / "catalog/runtime"


def adapter(
    registry: Registry,
    *,
    receipts_file: Path = RECEIPTS,
    **overrides: Path,
) -> ScientificCatalogFileAdapter:
    return ScientificCatalogFileAdapter(
        registry=registry,
        receipts_file=receipts_file,
        clock=lambda: FIXED_NOW,
        **overrides,
    )


async def test_candidate_catalog_is_truthful_about_access_identity_and_cache_state(registry: Registry) -> None:
    snapshot = await adapter(registry).list_models()

    assert snapshot.observed_at == FIXED_NOW
    by_id = {item.model_id: item for item in snapshot.data.items}
    assert sorted(by_id) == ["alphafold3", "rfdiffusion"]

    alpha_fold = by_id["alphafold3"]
    assert alpha_fold.readiness == "candidate"
    assert alpha_fold.access.profile == "academic"
    assert alpha_fold.access.state == "verified"
    assert alpha_fold.access.request_time_license_receipt_required is False
    assert alpha_fold.access.receipt_digest is None
    assert alpha_fold.access.authorization is not None
    assert alpha_fold.access.authorization.use_authorization_status == "Granted"
    assert alpha_fold.access.authorization.execution_authorization_status == "Authorized"
    assert alpha_fold.access.authorization.asset_id == "alphafold3"
    assert alpha_fold.access.formal_license_status == "FormalAcceptancePending"
    assert "Formal acceptance is advisory" in alpha_fold.access.gate
    assert alpha_fold.access.credentials_exposed is False
    assert alpha_fold.access.alternative is not None
    assert alpha_fold.access.alternative.model_id == "openfold3-openbind"
    # No exact fast-start observation is joined to a scientific backend yet, so
    # the tier must stay unobserved rather than inheriting a generic default.
    assert alpha_fold.caching.exact_tier == "not-observed"
    assert alpha_fold.caching.gpu_snapshot == "unavailable"

    # A standard-licence candidate must carry no academic authorization at all.
    rfdiffusion = by_id["rfdiffusion"]
    assert rfdiffusion.backend.backend_id == "rfdiffusion-upstream:native-upstream"
    assert "rfdiffusion-upstream" not in by_id
    assert rfdiffusion.access.profile == "standard"
    assert rfdiffusion.access.state == "not-required"
    assert rfdiffusion.access.authorization is None
    assert rfdiffusion.access.formal_license_status == "not-applicable"
    assert rfdiffusion.qualification.state == "identity-mismatch"
    assert "variant_id" in rfdiffusion.qualification.mismatched

    assert alpha_fold.execution_mode == "scientific-batch"
    assert alpha_fold.interactive_supported is True
    assert [value.value for value in alpha_fold.service_classes] == ["customer-batch", "interactive"]
    assert rfdiffusion.interactive_supported is False


async def test_catalog_adapter_fails_closed_for_unknown_or_oversized_receipts(
    registry: Registry,
    tmp_path: Path,
) -> None:
    malformed = tmp_path / "receipts.json"
    malformed.write_text(json.dumps({"schema": "unknown", "receipts": []}), encoding="utf-8")
    broken = ScientificCatalogFileAdapter(registry=registry, receipts_file=malformed)
    with pytest.raises(ScientificAdminSourceUnavailableError, match="schema is unsupported"):
        await broken.list_models()

    malformed.write_text("x" * (1024 * 1024 + 1), encoding="utf-8")
    with pytest.raises(ScientificAdminSourceUnavailableError, match="too large"):
        await broken.list_models()


def test_receipt_resolution_never_falls_back_to_another_catalog_root(tmp_path: Path) -> None:
    with pytest.raises(RegistryError, match="not installed"):
        scientific_receipts_file(tmp_path / "configured-catalog")


async def test_catalog_adapter_blocks_only_the_model_whose_deployment_authorization_is_not_granted(
    registry: Registry,
    tmp_path: Path,
) -> None:
    readiness = json.loads(ACADEMIC_READINESS.read_text(encoding="utf-8"))
    alpha_fold = next(item for item in readiness["models"] if item["model_id"] == "alphafold3")
    alpha_fold["execution_authorization_status"] = "NotAuthorized"
    readiness_file = tmp_path / "academic-asset-readiness.json"
    readiness_file.write_text(json.dumps(readiness), encoding="utf-8")

    snapshot = await adapter(registry, academic_readiness_file=readiness_file).list_models()
    by_id = {item.model_id: item for item in snapshot.data.items}

    assert by_id["alphafold3"].access.state == "blocked"
    assert by_id["rfdiffusion"].readiness == "candidate"


@pytest.mark.parametrize(
    "serving_admission",
    ["AdmittedNoPerRequestLicenseReceipt", "PendingRuntimeReadiness"],
)
async def test_authorized_academic_model_is_never_projected_as_blocked_or_unknown(
    registry: Registry,
    tmp_path: Path,
    serving_admission: str,
) -> None:
    """Deployment-bound authorization holds whether or not the runtime is admitted yet.

    Platform deployment can still be pending; that must not downgrade the
    access projection to a blocked or unknown state.
    """

    readiness = json.loads(ACADEMIC_READINESS.read_text(encoding="utf-8"))
    readiness["models"][0]["serving_admission"] = serving_admission
    readiness_file = tmp_path / "academic-asset-readiness.json"
    readiness_file.write_text(json.dumps(readiness), encoding="utf-8")

    snapshot = await adapter(registry, academic_readiness_file=readiness_file).list_models()
    alpha_fold = next(item for item in snapshot.data.items if item.model_id == "alphafold3")

    assert alpha_fold.access.state == "verified"
    assert alpha_fold.readiness in {"candidate", "qualified"}
    assert alpha_fold.access.authorization is not None
    assert alpha_fold.access.authorization.use_authorization_status == "Granted"
    assert alpha_fold.access.authorization.execution_authorization_status == "Authorized"
    assert alpha_fold.access.request_time_license_receipt_required is False


async def test_catalog_adapter_never_turns_a_request_time_licence_receipt_into_a_requirement(
    registry: Registry,
    tmp_path: Path,
) -> None:
    """Academic use is deployment-bound; a per-request receipt is never a gate."""

    readiness = json.loads(ACADEMIC_READINESS.read_text(encoding="utf-8"))
    readiness["request_time_license_receipt_required"] = True
    readiness_file = tmp_path / "academic-asset-readiness.json"
    readiness_file.write_text(json.dumps(readiness), encoding="utf-8")

    snapshot = await adapter(registry, academic_readiness_file=readiness_file).list_models()
    alpha_fold = next(item for item in snapshot.data.items if item.model_id == "alphafold3")

    assert alpha_fold.access.request_time_license_receipt_required is False
    assert alpha_fold.access.state == "blocked"
    assert "contradicts deployment-bound admission" in alpha_fold.access.gate


async def test_delivered_catalog_joins_every_published_candidate(registry: Registry) -> None:
    delivered = ScientificCatalogFileAdapter(
        registry=registry,
        receipts_file=scientific_receipts_file(DELIVERED_CATALOG),
        clock=lambda: FIXED_NOW,
    )
    snapshot = await delivered.list_models()

    assert len(snapshot.data.items) == 10
    by_candidate = {item.candidate_id: item for item in snapshot.data.items}
    assert set(by_candidate) == {
        "alphafold3",
        "bindcraft",
        "boltzgen",
        "esmfold2",
        "esmfold2-fast",
        "mosaic",
        "openfold3-openbind",
        "proteina-complexa",
        "protenix-v2",
        "rfdiffusion-upstream",
    }
    assert all(item.workload_profile == "published" for item in by_candidate.values())
    boltzgen = by_candidate["boltzgen"]
    assert boltzgen.workload_profile == "published"
    assert boltzgen.readiness == "candidate"
    assert boltzgen.backend.source_repository == "HannesStark/boltzgen"
    assert boltzgen.backend.source_revision == "31d9d9b9c72245b4ed6fe8742d6fbf4e1a3552a0"
    assert boltzgen.backend.model_revision == "31d9d9b9c72245b4ed6fe8742d6fbf4e1a3552a0"
    assert boltzgen.backend.runtime_image_digest == (
        "sha256:9c3230424e02d725dc145b8f21a18f283910e1beba1f37466598ee832813820e"
    )
    assert boltzgen.backend.execution_identity_digest == (
        "1e79a35d5560421f6ca276ebb995cce6354343e1d89045a4d6b67a4c394a4fe4"
    )
    assert boltzgen.available_upgrade is not None
    assert boltzgen.available_upgrade.source_repository == "HannesStark/boltzgen"
    assert boltzgen.available_upgrade.source_revision == "a3149cf18eeb58648d1abbb27539bd73f746cdda"
    assert boltzgen.available_upgrade.state == "available-unqualified"
    assert "qualified-evidence" in boltzgen.missing_evidence
    assert "source-identity-agreement" not in boltzgen.missing_evidence
    assert not any(
        issue.candidate_id == "boltzgen" and issue.source == "workload-profile"
        for issue in snapshot.data.projection_issues
    )
    assert by_candidate["proteina-complexa"].workload_profile == "published"
    openfold = by_candidate["openfold3-openbind"]
    assert openfold.workload_profile == "published"
    assert openfold.readiness == "candidate"
    assert openfold.backend.source_repository == "aqlaboratory/openfold-3"
    assert openfold.backend.source_revision == "c4771653c5d0a3ebb0b3af71b05efd64bc44ee86"
    assert openfold.backend.model_revision == "c4771653c5d0a3ebb0b3af71b05efd64bc44ee86"
    assert "qualified-evidence" in openfold.missing_evidence
    assert by_candidate["mosaic"].workload_profile == "published"
    assert by_candidate["mosaic"].readiness == "candidate"
    assert "qualified-evidence" in by_candidate["mosaic"].missing_evidence
    rfdiffusion = by_candidate["rfdiffusion-upstream"]
    assert rfdiffusion.model_id == "rfdiffusion"
    assert rfdiffusion.workload_profile == "published"
    assert rfdiffusion.backend.source_repository == "RosettaCommons/RFdiffusion"
    assert rfdiffusion.backend.model_revision == "9273ef67335acaf91df0150473a274759229cdf6"
    assert "workload-profile" not in rfdiffusion.missing_evidence


async def test_invalid_profile_is_isolated_to_its_candidate(registry: Registry, tmp_path: Path) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profiles["profiles"][0]["schema"] = "unsupported"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(registry, profiles_file=profiles_file).list_models()
    by_candidate = {item.candidate_id: item for item in snapshot.data.items}

    assert by_candidate["alphafold3"].workload_profile == "absent"
    assert by_candidate["alphafold3"].readiness == "unknown"
    assert by_candidate["rfdiffusion-upstream"].workload_profile == "published"
    assert any(
        issue.candidate_id == "alphafold3" and issue.source == "workload-profile"
        for issue in snapshot.data.projection_issues
    )


async def test_unavailable_optional_catalog_sources_degrade_rows_without_failing_the_list(
    registry: Registry,
    tmp_path: Path,
) -> None:
    invalid = tmp_path / "invalid.json"
    invalid.write_text("{}", encoding="utf-8")

    snapshot = await adapter(
        registry,
        variants_file=invalid,
        profiles_file=invalid,
        academic_readiness_file=invalid,
    ).list_models()

    assert len(snapshot.data.items) == 2
    assert all(item.readiness == "unknown" for item in snapshot.data.items)
    assert all(item.workload_profile == "absent" for item in snapshot.data.items)
    assert {issue.source for issue in snapshot.data.projection_issues} == {
        "academic-readiness",
        "variant-map",
        "workload-profile",
    }


async def test_projection_issue_isolation_is_bounded(registry: Registry, tmp_path: Path) -> None:
    receipts_file = tmp_path / "scientific-source-candidate-receipts.json"
    receipts_file.write_text(
        json.dumps(
            {
                "schema": "fs2-serve.nebius.ai/scientific-source-candidate-receipts/v1",
                "receipts": [{"model_id": f"candidate-{index:03d}"} for index in range(256)],
            }
        ),
        encoding="utf-8",
    )
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(
        json.dumps(
            {
                "schema": "fs2-serve.nebius.ai/scientific-workload-profiles/v1",
                "profiles": [{"model_id": f"profile-{index:03d}", "schema": "unsupported"} for index in range(256)],
            }
        ),
        encoding="utf-8",
    )
    academic_file = tmp_path / "academic-asset-readiness.json"
    academic_file.write_text(
        json.dumps(
            {
                "schema": "fs2-serve.nebius.ai/academic-asset-readiness/v1",
                "request_time_license_receipt_required": False,
                "models": [{"model_id": f"academic-{index:03d}"} for index in range(64)],
            }
        ),
        encoding="utf-8",
    )
    variants_file = tmp_path / "model-variants.json"
    variants_file.write_text(
        json.dumps({"fallback_candidates": {f"variant-{index:03d}": {} for index in range(256)}}),
        encoding="utf-8",
    )

    snapshot = await adapter(
        registry,
        receipts_file=receipts_file,
        profiles_file=profiles_file,
        academic_readiness_file=academic_file,
        variants_file=variants_file,
    ).list_models()

    assert len(snapshot.data.items) == 256
    assert len(snapshot.data.projection_issues) == 256
    assert all(item.readiness == "unknown" for item in snapshot.data.items)


async def test_duplicate_candidate_receipts_never_trust_the_first_row(registry: Registry, tmp_path: Path) -> None:
    receipts = json.loads(RECEIPTS.read_text(encoding="utf-8"))
    receipts["receipts"].append(dict(receipts["receipts"][0]))
    receipts_file = tmp_path / "scientific-source-candidate-receipts.json"
    receipts_file.write_text(json.dumps(receipts), encoding="utf-8")

    snapshot = await adapter(
        registry,
        receipts_file=receipts_file,
        variants_file=FIXTURES / "model-variants.json",
        profiles_file=FIXTURES / "scientific-workload-profiles.json",
        academic_readiness_file=ACADEMIC_READINESS,
    ).list_models()
    alpha_fold = [item for item in snapshot.data.items if item.candidate_id == "alphafold3"]

    assert len(alpha_fold) == 1
    assert alpha_fold[0].readiness == "unknown"
    assert alpha_fold[0].access.profile == "academic"
    assert alpha_fold[0].access.state == "unverified"
    assert any(
        issue.candidate_id == "alphafold3" and issue.source == "candidate-receipt" and "duplicated" in issue.reason
        for issue in snapshot.data.projection_issues
    )


async def test_mapped_candidate_with_no_allowed_variant_cannot_borrow_lane_qualification(
    registry: Registry,
    tmp_path: Path,
) -> None:
    variants = json.loads((FIXTURES / "model-variants.json").read_text(encoding="utf-8"))
    variants["fallback_candidates"]["rfdiffusion-upstream"]["profile_variants"] = {
        "portable": None,
        "blackwell": None,
    }
    variants_file = tmp_path / "model-variants.json"
    variants_file.write_text(json.dumps(variants), encoding="utf-8")

    snapshot = await adapter(registry, variants_file=variants_file).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.qualification.state == "identity-mismatch"
    assert "variant_id" in rfdiffusion.qualification.mismatched


def test_signed_promoted_variant_cannot_override_an_unqualified_candidate_contract(
    registry: Registry,
) -> None:
    runtime_digest = "sha256:" + "7" * 64
    source_revision = "8" * 40
    base = registry.get("rfdiffusion", require_enabled=False)
    promoted = replace(
        base,
        gateway=replace(base.gateway, routable=True, runtime_image_digest=runtime_digest),
        variant_id="rfdiffusion-upstream-portable",
        variant_digest="9" * 64,
        variant_valid_until="2099-01-01T00:00:00Z",
    )

    qualification = _execution_identity_join(
        candidate_id="rfdiffusion-upstream",
        route_scope=CandidateRouteScope(
            lane_id="rfdiffusion",
            variant_ids=frozenset({"rfdiffusion-upstream-portable"}),
            mapped=True,
        ),
        backend_identity="native-upstream",
        operational=promoted,
        execution_identity={
            "model_revision": source_revision,
            "runtime_image_digest": runtime_digest,
        },
    )

    assert qualification.state == "evidence-absent"
    assert qualification.mismatched == []
    assert qualification.compared == ["runtime_image_digest", "variant_id"]
    assert "explicitly remain unqualified" in qualification.reason


async def test_mapped_candidate_never_inherits_the_serving_lane_profile(
    registry: Registry,
    tmp_path: Path,
) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profiles["profiles"][1]["model_id"] = "rfdiffusion"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(registry, profiles_file=profiles_file).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.workload_profile == "absent"
    assert rfdiffusion.readiness == "unknown"
    assert rfdiffusion.backend.model_revision is None


async def test_exact_model_mapping_binds_a_lane_profile_only_for_the_same_source_family(
    registry: Registry,
    tmp_path: Path,
) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profiles["profiles"][1]["model_id"] = "rfdiffusion"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")
    variants = json.loads((FIXTURES / "model-variants.json").read_text(encoding="utf-8"))
    variants["fallback_candidates"]["rfdiffusion-upstream"]["relationship"] = "exact-model"
    variants_file = tmp_path / "model-variants.json"
    variants_file.write_text(json.dumps(variants), encoding="utf-8")

    snapshot = await adapter(
        registry,
        profiles_file=profiles_file,
        variants_file=variants_file,
    ).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.model_id == "rfdiffusion"
    assert rfdiffusion.workload_profile == "published"
    assert rfdiffusion.backend.model_revision == "4444444444444444444444444444444444444444"

    profiles["profiles"][1]["source"]["repository"] = "untrusted-fork/RFdiffusion"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")
    snapshot = await adapter(
        registry,
        profiles_file=profiles_file,
        variants_file=variants_file,
    ).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.workload_profile == "absent"
    assert rfdiffusion.readiness == "unknown"
    assert rfdiffusion.backend.model_revision is None


async def test_same_revision_in_a_different_repository_is_not_the_same_candidate(
    registry: Registry,
    tmp_path: Path,
) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profiles["profiles"][1]["source"]["repository"] = "untrusted-fork/RFdiffusion"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(registry, profiles_file=profiles_file).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.readiness == "unknown"
    assert rfdiffusion.qualification.state == "identity-mismatch"
    assert rfdiffusion.backend.source_repository == "untrusted-fork/RFdiffusion"
    assert rfdiffusion.backend.source_revision == "4444444444444444444444444444444444444444"
    assert rfdiffusion.available_upgrade is None
    assert any(
        issue.candidate_id == "rfdiffusion-upstream" and issue.source == "workload-profile"
        for issue in snapshot.data.projection_issues
    )


async def test_same_repository_revision_drift_is_an_upgrade_but_source_kind_drift_is_a_conflict(
    registry: Registry,
    tmp_path: Path,
) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profile = profiles["profiles"][1]
    profile["source"]["kind"] = "archive"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(registry, profiles_file=profiles_file).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.readiness == "unknown"
    assert rfdiffusion.qualification.state == "identity-mismatch"
    assert rfdiffusion.backend.source_repository == "RosettaCommons/RFdiffusion"
    assert rfdiffusion.backend.source_revision == "4444444444444444444444444444444444444444"
    assert rfdiffusion.available_upgrade is None
    assert "source-identity-agreement" in rfdiffusion.missing_evidence


async def test_global_catalog_qualifies_only_a_complete_pinned_profile(
    registry: Registry,
    tmp_path: Path,
) -> None:
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profile = profiles["profiles"][1]
    profile["state"] = "qualified"
    profile["route_exposed"] = True
    profile["semantic_validation"] = {"state": "qualified"}
    profile["execution_identity"]["artifact_manifest_digest"] = "7" * 64
    profile["execution_identity"]["execution_identity_sha256"] = "8" * 64
    profile["qualification"] = {
        "h100_semantic_receipt_sha256": "1" * 64,
        "public_completion_receipt_sha256": "2" * 64,
        "scheduler_eligibility_receipt_sha256": "3" * 64,
        "execution_map_sha256": "4" * 64,
        "qualified_at": "2026-09-04T12:00:00Z",
    }
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(registry, profiles_file=profiles_file).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.readiness == "qualified"
    assert rfdiffusion.qualification.state == "qualified"
    assert rfdiffusion.backend.source_revision == "4444444444444444444444444444444444444444"
    assert rfdiffusion.available_upgrade is None
    assert "qualified-evidence" not in rfdiffusion.missing_evidence


async def test_missing_academic_asset_identity_is_not_synthesised(registry: Registry, tmp_path: Path) -> None:
    readiness = json.loads(ACADEMIC_READINESS.read_text(encoding="utf-8"))
    readiness["models"][0].pop("asset_id")
    readiness_file = tmp_path / "academic-asset-readiness.json"
    readiness_file.write_text(json.dumps(readiness), encoding="utf-8")

    snapshot = await adapter(registry, academic_readiness_file=readiness_file).list_models()
    alpha_fold = next(item for item in snapshot.data.items if item.candidate_id == "alphafold3")

    assert alpha_fold.readiness == "unknown"
    assert alpha_fold.access.state == "unverified"
    assert alpha_fold.access.authorization is None
    assert any(
        issue.candidate_id == "alphafold3" and issue.source == "academic-readiness" and "asset identity" in issue.reason
        for issue in snapshot.data.projection_issues
    )


async def test_access_sources_can_narrow_but_never_upgrade_a_blocked_receipt(
    registry: Registry,
    tmp_path: Path,
) -> None:
    receipts = json.loads(RECEIPTS.read_text(encoding="utf-8"))
    receipts["receipts"][1]["access_state"] = "blocked"
    receipts_file = tmp_path / "scientific-source-candidate-receipts.json"
    receipts_file.write_text(json.dumps(receipts), encoding="utf-8")
    profiles = json.loads((FIXTURES / "scientific-workload-profiles.json").read_text(encoding="utf-8"))
    profiles["profiles"][1]["access"]["state"] = "verified"
    profiles_file = tmp_path / "scientific-workload-profiles.json"
    profiles_file.write_text(json.dumps(profiles), encoding="utf-8")

    snapshot = await adapter(
        registry,
        receipts_file=receipts_file,
        variants_file=FIXTURES / "model-variants.json",
        profiles_file=profiles_file,
        academic_readiness_file=ACADEMIC_READINESS,
    ).list_models()
    rfdiffusion = next(item for item in snapshot.data.items if item.candidate_id == "rfdiffusion-upstream")

    assert rfdiffusion.access.state == "blocked"
    assert rfdiffusion.readiness == "blocked"


class DiscoveryService:
    def discovery_profiles(self, *, tenant_id, allowed_models, surface):
        assert allowed_models == frozenset({"*"})
        assert surface == "admin"
        if tenant_id != "tenant-a":
            return ()
        return (
            ScientificProfileDiscovery(
                model_id="protein-design",
                display_name="Protein Design",
                execution_mode="scientific-batch",
                operations=("design",),
                service_classes=("customer-batch",),
                parameter_schema="fs2-serve.nebius.ai/protein-design-parameters/v1",
                source_repository="example/protein-design",
                source_revision="a" * 40,
                variant_id="protein-design-h100",
                runtime_image_digest="sha256:" + "b" * 64,
                execution_identity_sha256="c" * 64,
                access_profile="standard",
                access_state="not-required",
                access_receipt_digest=None,
                h100_semantic_receipt_sha256="d" * 64,
                public_completion_receipt_sha256="e" * 64,
                scheduler_eligibility_receipt_sha256="f" * 64,
                execution_map_sha256="1" * 64,
                qualified_at="2026-09-03T08:00:00Z",
                mcp_tool_name="submit_protein_design",
                mcp_description="Submit a qualified protein design run.",
            ),
        )


class GlobalCatalog:
    def __init__(self) -> None:
        self.calls = 0

    async def list_models(self, *, tenant_id: str | None = None) -> ScientificModelSnapshot:
        assert tenant_id is None
        self.calls += 1
        return ScientificModelSnapshot(
            data=ScientificModelReadinessList(items=[]),
            observed_at=FIXED_NOW,
        )


async def test_admin_discovery_lists_only_tenant_submittable_profiles() -> None:
    adapter = ScientificProfileDiscoveryAdapter(
        scientific_batches=DiscoveryService(),  # type: ignore[arg-type]
        clock=lambda: FIXED_NOW,
    )

    assert (await adapter.list_models()).data.items == []
    snapshot = await adapter.list_models(tenant_id="tenant-a")

    assert snapshot.observed_at == FIXED_NOW
    assert [item.model_id for item in snapshot.data.items] == ["protein-design"]
    model = snapshot.data.items[0]
    assert model.readiness == "qualified"
    assert model.backend.runtime_image_digest == "sha256:" + "b" * 64
    assert model.backend.execution_identity_digest == "c" * 64


async def test_admin_discovery_preserves_global_candidate_catalog_without_bypassing_tenant_filter() -> None:
    global_catalog = GlobalCatalog()
    adapter = ScientificProfileDiscoveryAdapter(
        scientific_batches=DiscoveryService(),  # type: ignore[arg-type]
        global_catalog=global_catalog,
        clock=lambda: FIXED_NOW,
    )

    assert (await adapter.list_models()).data.items == []
    assert global_catalog.calls == 1
    tenant_snapshot = await adapter.list_models(tenant_id="tenant-a")
    assert [item.model_id for item in tenant_snapshot.data.items] == ["protein-design"]
    assert global_catalog.calls == 1


class ProfileStateConsistencyTests(unittest.TestCase):
    """A candidate is never routed; a dispatchable or qualified profile always is."""

    def test_accepted_pairs(self) -> None:
        from fs2_serve.scientific_admin_catalog import _profile_state_is_consistent
        from fs2_serve.scientific_batch.adapters.common import profile_state_is_consistent

        for state, routed in (("candidate-unqualified", False), ("active", True), ("qualified", True)):
            with self.subTest(state=state, route_exposed=routed):
                self.assertTrue(_profile_state_is_consistent(state, routed))
                self.assertTrue(profile_state_is_consistent(state, routed))

    def test_rejected_mismatches(self) -> None:
        from fs2_serve.scientific_admin_catalog import _profile_state_is_consistent
        from fs2_serve.scientific_batch.adapters.common import profile_state_is_consistent

        for state, routed in (
            ("candidate-unqualified", True),
            ("active", False),
            ("qualified", False),
            ("unknown-state", True),
            ("unknown-state", False),
        ):
            with self.subTest(state=state, route_exposed=routed):
                self.assertFalse(_profile_state_is_consistent(state, routed))
                self.assertFalse(profile_state_is_consistent(state, routed))
