{{- range $component, $name := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels: {app.kubernetes.io/name: fs2-public-edge-{{ $component | lower }}, app.kubernetes.io/part-of: fs2-public-edge-boundary}
automountServiceAccountToken: false
{{- end }}
