apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cancer-immunotherapy-academic-assets-rwx-v1
  namespace: fs2-models
  labels:
    app.kubernetes.io/name: cancer-immunotherapy-academic-assets
    app.kubernetes.io/part-of: fs2-serve
    app.kubernetes.io/managed-by: fs2-academic-assets-ingestion
  annotations:
    fs2.nebius.ai/data-classification: licensed-academic-nonredistributable
    fs2.nebius.ai/filesystem-id: computefilesystem-e00hdb1drrgsenr2j7
    fs2.nebius.ai/region: eu-north1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-mounted-fs-path-sc
  volumeMode: Filesystem
